services:
  - type: web
    name: research-api
    runtime: docker
    envVars:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GMAIL_SMTP_USERNAME
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: MAIL_SMTP_PORT
        value: "465"
      - key: MAIL_SMTP_SSL
        value: "true"
      - key: MAIL_SMTP_STARTTLS
        value: "false"
      - key: MAIL_SENDER_NAME
        value: Biochemical and Environmental Research Lab
      - key: MAIL_SENDER_EMAIL
        sync: false
